server:
  port: 9095
  address: 0.0.0.0

spring:
  thymeleaf:
    cache: true
    encoding: utf-8
    enabled: true
    prefix: classpath:/static/
    suffix: .html
  datasource:
    # url: jdbc:mysql://localhost:3306/gateway?useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://localhost:3306/gateway?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true&nullNamePatternMatchesAll=true
    username: wcmbpm
    password: P@ssw0rd
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mappers/*.xml


gateway:
  sync:
    websocket:
        enabled : true
#    http:
#      enabled: true

logging:
  level:
    root: info
    org.springframework.boot: info
    org.apache.ibatis: info
    com.bpwizard.gateway.bonuspoint: info
    com.bpwizard.gateway.lottery: info
    com.bpwizard.gateway: info
