
# app:
#   name: "@project.artifactId@"
#   version: "@project.version@"
security:
  require-ssl: true
server:
  port: 8843
  servlet:
    context-path: "/configserver"
  # The format used for the keystore. It could be set to JKS in case it is a JKS file
  ssl:
    enabled: true
    #key-store-type: PKCS12
    key-store-type: JKS
    # client-auth: need
    # The path to the keystore containing the certificate
    key-store: classpath:jks/config-server.jks
    # The password used to generate the certificate
    key-store-password: Passw0rd
    # The alias mapped to the certificate
    key-alias: config-server-ssl
    trust-store: classpath:jks/config-server.jks
    trust-store-password: Passw0rd
    trust-store-type: JKS
spring:
  app:
    name: config-server
  profiles:
    active: jdbc


logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    com.bpwizard.config: INFO
    
# for actuator endpoints (spring boot 2)
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    logfile:
      external-file: "/var/log/cfgserver/configserver.log"