
app:
  name: "@project.artifactId@"
  version: "@project.version@"

server:
  port: 8888
  servlet:
    context-path: "/configserver"
spring:
  profiles:
    active: jdbc


logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    com.bpwizard.config: INFO
    
# for actuator endpoints (spring boot 2)
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    logfile:
      external-file: "/var/log/cfgserver/configserver.log"