spring:
    application:
      name: authoring_ui_ssl
# security:
  # require-ssl: true
server:
  contextPath: /
  servlet:
    session.persistent: false
  port: 3000
#  ssl:
#    enabled: true
#    # client-auth: need
#    key-store: classpath:jks/authoring-ui-client.jks
#    key-store-password: Passw0rd
#    key-alias: authoring_ui_ssl
#    key-store-type: JKS
#    #key-store-provider: SUN
#    trust-store: classpath:jks/authoring-ui-client.jks
#    trust-store-password: Passw0rd
#    trust-store-type: JKS

endpoint:
  ms-service: https://localhost:8843/configserver/api/props