apiVersion: "v1"
kind: "Secret"
metadata:
  name: "wcm-database-secret"
stringData:
  user: "wcm"
  password: "P@ssw0rd"
---  
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "bpm-database-secret"
stringData:
  user: "bpm"
  password: "P@ssw0rd"
---  
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "gateway-database-secret"
stringData:
  user: "gateway"
  password: "P@ssw0rd"  
---  
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "account-database-secret"
stringData:
  user: "account"
  password: "P@ssw0rd"  
---  
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "ignite-database-secret"
stringData:
  user: "ignite"
  password: "P@ssw0rd"  
---
piVersion: "v1"
kind: "Secret"
metadata:
  name: "soul-database-secret"
stringData:
  user: "soul"
  password: "P@ssw0rd"  
---
piVersion: "v1"
kind: "Secret"
metadata:
  name: "boot-database-secret"
stringData:
  user: "boot"
  password: "P@ssw0rd" 

