version: '3'
services:
    camunda:
        build: .
        environment:
          - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom -Duser.timezone=America/Montreal
        ports:
          - "8055:8080"
          - "9999:9999"
        networks:
          - prometheus-grafana_monitor-net
        volumes:
          - ./docker/volumes/customcollectors:/customcollectors/
          - ./docker/volumes/camunda_prometheus:/camunda_prometheus/
networks:
    prometheus-grafana_monitor-net:
        external: true