---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/openshift-demo
    fabric8.io/scm-tag: HEAD
  labels:
    app: openshift-demo
    provider: fabric8
    version: 0.0.1-SNAPSHOT
    group: com.bpwizard.openshift
  name: openshift-demo
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    app: openshift-demo
    provider: fabric8
    group: com.bpwizard.openshift
  strategy:
    rollingParams:
      timeoutSeconds: 3600
    type: Rolling
  template:
    metadata:
      annotations:
        fabric8.io/scm-tag: HEAD
        fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/openshift-demo
      labels:
        app: openshift-demo
        provider: fabric8
        version: 0.0.1-SNAPSHOT
        group: com.bpwizard.openshift
    spec:
      containers:
      - env:
        - name: jasypt.encryptor.password
          value: password
        - name: LOG_ROOT_LEVEL
          value: value
        - name: APP_LOG_LEVEL
          value: TRACE
        - name: log.root.dir
          value: "/var/logs/wcm-bpm-boot"
        - name: spring.profiles.active
          value: openshift
        - name: DB_HOST_PORT
          value: mysql:3306
        - name: DB_DATABASE
          value: wcm_bpm
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: user
              name: wcm-bpm-database-secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: wcm-bpm-database-secret
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: "image-registry.openshift-image-registry.svc:5000/wcm-bpm/openshift-demo:latest"
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
        name: spring-boot
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
        securityContext:
          privileged: false
  triggers:
  - type: ConfigChange
