spring.application.name: simpleApplication
server.port: 10100
spring:
  datasource:
    url: jdbc:h2:mem:camunda;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
camunda:
  bpm:
    application:
      isDeleteUponUndeploy: false
      isScanForProcessDefinitions: false
      isDeployChangedOnly: true
      isResumePreviousVersions: true
      resumePreviousBy: a value
    job-execution:
      enabled: true
    metrics:
      enabled: false
      db-reporter-activate: false
    default-serialization-format: application/json
    authorization:
      enabled: true
    history-level: activity
    id-generator: simple
    admin-user:
      id: admin
      password: admin