server:
  port: 8080

kc:
  base-url: http://localhost:8080/auth
  realm: wcm_bpm
  realm-url: ${kc.base-url}/realms/${kc.realm}

spring:
  security:
    oauth2:
      client:
        registration:
          demo:
            client-id: wcm_bpm
            client-name: wcm_bpm
            client-secret: bdaedae5-8aed-4d3c-a079-3077fc355bbe
            provider: keycloak
            authorization-grant-type: authorization_code
            scope: openid, profile
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            authorization-uri: ${kc.realm-url}/protocol/openid-connect/auth
            jwk-set-uri: ${kc.realm-url}/protocol/openid-connect/certs
            token-uri: ${kc.realm-url}/protocol/openid-connect/token
# would be cool if there was a end-session-uri to propagate logouts 

#  User info endpoint not needed since Keycloak uses self-contained value tokens
#            user-info-uri: ${kc.realm-url}/protocol/openid-connect/userinfo
            #user-name-attribute: preferred_username
            user-name-attribute: user_name