server:
  port: 9090
camunda:
  bpm:
    client:
      base-url: http://localhost:8080/rest
      # base-url: http://localhost:8080/api/engine/engine/default
      worker-id: spring-boot-client

logging:
  level:
    org.camunda.bpm.client: info
