name: bpw_renderer
description: bpw_renderer Dar package.
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  bloc: ^6.1.0
  equatable: ^1.2.5
  flutter_bloc: ^6.0.6
  flutter_i18n: ^0.20.0
  font_awesome_flutter: ^8.8.1
  google_fonts: ^1.1.0
  google_maps_flutter: ^0.5.27+3
  http: ^0.12.2
  logging: ^0.11.4
  material_design_icons_flutter: ^4.0.5655
  path_provider: ^1.6.21
  provider: ^4.3.2+2
  shared_preferences: ^0.5.12
  bpw_common:
    path: ../bpw_common
