spec:
  template:
    spec:
      serviceAccountName: "wcm-bpm"
      volumes:
        - name: "wcm-bpm-config"
          secret:
            # The secret must be created before deploying this application
            secretName: "wcm-bpm-config"
      containers:
        - env:
          - name: "spring.profiles.active"
              value: "k8s"    
            - name: JAEGER_ENDPOINT
              value: "http://jaeger-collector.istio-system.svc:14268/api/traces"
            - name: JAEGER_REPORTER_LOG_SPANS
              value: "true"
            - name: JAEGER_SAMPLER_TYPE
              value: const
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
            - name: JAEGER_PROPAGATION
              value: b3
            - name: DB_HOST_PORT
              value: "mysql:3306"
            - name: DB_DATABASE
              value: boot
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: user
                  name: gateway-database-secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: gateway-database-secret
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: "jasypt.encryptor.password"
              value: password
            - name: ROOT_LOG_LEVEL
              value: WARN
            - name: APP_LOG_LEVEL
              value: INFO
            - name: SQL_LOG_LEVEL
              value: WARN
          image: "container-registry:32000/gateway-admin-boot:latest"
          imagePullPolicy: IfNotPresent
          livenessProbe:
           httpGet:
             path: /actuator/health
             port: 8080
             scheme: HTTP
           initialDelaySeconds: 180
          readinessProbe:
           httpGet:
             path: /actuator/health
             port: 8080
             scheme: HTTP
           initialDelaySeconds: 20
          volumeMounts:
            - name: "gateway-admin-boot-directory"
              mountPath: "/var/spring-logs/gateway-admin-boot"
            - name: "gateway-admin-boot-secret-config"
              readOnly: true
              # Mount the secret where spring-cloud-kubernetes is configured to read it
              # see src/main/resources/bootstrap.yml
              mountPath: "/etc/secrets/gateway-admin-boot"
          # resources:
#            # requests:
#              # cpu: "0.2"
#              # memory: 256Mi
#            # limits:
#              # cpu: "1.0"
#              # memory: 256Mi
      volumes:
        - name: "wcm-bpm-log-directory"
          hostPath:
            path: /home/ubuntu/logs/gateway-admin-boot
          # emptyDir: {}
        - name: "gateway-admin-boot-secret-config"
          secret:
            # The secret must be created before deploying this application
            secretName: "gateway-database-secret"