version: '3.3'
services:
  auth-server:
    build: api-key-ear
    environment:
      REALM_NAME: example
    command: ["-Dkeycloak.migration.action=import", "-Dkeycloak.migration.provider=dir", "-Dkeycloak.migration.dir=/import", "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"]
    volumes:
      - ./api-key-ear/import:/import
    ports:
    - "8080:8080"
  dashboard-service:
    build: dashboard-service
    environment:
      REALM_NAME: example
    ports:
    - "8180:8180"
  rest-api-service:
    build: rest-api-service
    environment:
      REALM_NAME: example
      AUTH_SERVER_URL: auth-server:8080
    ports:
    - "8280:8280"
