test:
  property1: test_prop1_value
#actutator /actuator/health, /actuator/metrics, /actuator/beans
management:
  endpoints:
    #shutdown:
    #  enabled: true
    #health:
    #  show-details: always
    web:
      exposure:
        include: "*"
  #endpoint:        
    #metrics:
      #enabled: true
    #prometheus:
      #enabled: true
  #metrics:
    #export:
      #prometheus:
        #enabled: true
#management.endpoint.metrics.enabled=true
#management.endpoints.web.exposure.include=*
#management.endpoints.web.exposure.include=health,info,metrics,prometheus
#management.endpoint.prometheus.enabled=true
#management.metrics.export.prometheus.enabled=true              
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: "jdbc:mysql://${DB_HOST_PORT}/${DB_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true&nullNamePatternMatchesAll=true"
    # url: "jdbc:mysql://mysql:3306/${DB_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true&nullNamePatternMatchesAll=true"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    
    #url: "jdbc:mysql://localhost:3306/wcm_bpm?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true&nullNamePatternMatchesAll=true"
    #username: wcmbpm
    #password: P@ssw0rd
    driver-class-name: com.mysql.jdbc.Driver    
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000
    hikari:
      connection-test-query: select 1
      # idle-timeout: 5000
      idle-timeout: 600000
      # max-lifetime: 120000
      max-lifetime: 1800000
      maximum-pool-size: 5
      minimum-idle: 5
      # connectionTimeout: 30000  


opentracing:
  jaeger:
    http-sender:
      #url: "http://jaeger-all-in-one-inmemory-collector.jaeger:14268/api/traces"
      #url: "http://jaeger-all-in-one-inmemory-collector-headless.jaeger:14268/api/traces"
      url: "http://jaeger-all-in-one-inmemory-collector-headless.jaegers:14268/api/traces"
      username: kubeadmin
      password: "mhk2X-Y8ozE-9icYb-uLCdV"
      #authtoken: token
    log-spans: true
    service-name: openshift-demo
    enable-b3-propagation: true
#---
#spring:
#  profiles: local
#opentracing:
#  jaeger:
#    http-sender:
#      url: http://jaeger-collector-dev.2886795293-80-kitek02.environments.katacoda.com/api/traces