## Spring Commons demo properties

# Spring related properties
spring:
  #resources.static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/webui/
  # Active profile
  profiles.active: dev
  application:
    name: wcm-boot
  # JSON serialization settings
  jackson:
    default-property-inclusion: NON_NULL
    
    serialization:
      write-null-map-values: false 
      
    deserialization:
      accept-single-value-as-array: true
  devtools:
    # Comment this if you want the app to restart
    # when source code changes
    restart.enabled: false
    livereload.enabled: false
    
  # https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes#bean-overriding
  main.allow-bean-definition-overriding: true

springfox:
    documentation:
      swagger:
        v2:
          path: /api-docs
server:
  contextPath: /
  # servlet.session.persistent: false
  # port: 19090
  port: ${PORT:8080}
# Spring Commons related properties
bpw:

  # prepopulate Users and Roles
  rolename: 
    - admin
    - wcm-viewer
    - user
    - readonly
    - readwrite
    - camunda-admin
    - UNVERIFIED
    - BLOCKED
  

  user:
    -
      username: myadmin@example.com
      email: myadmin@example.com
      password: admin!
      rolename: 
        - admin
    -
      username: demo
      email: mydemo@example.com
      password: demo
      rolename:
        - admin 
        - readonly
        - wcm-viewer
        - camunda-admin
    # Spring Commons flags
    # enabled:
      # json-prefix: false
      
  # Properties to be passed to client
  shared:
    fooBar: 123...
#jasypt:
#  encryptor:
#    password: password