spring:
  datasource:
    #url: jdbc:h2:~/camunda;DB_CLOSE_ON_EXIT=false
    url: jdbc:h2:mem:camunda;DB_CLOSE_ON_EXIT=false
#spring.datasource.url=jdbc:h2:mem:camunda
#spring.datasource.url=jdbc:mysql://localhost:3306/process-engine
#spring.datasource.username=camunda
#spring.datasource.password=camunda
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver

restProxyHost: localhost
restProxyPort: 8080

rabbitmqHost: localhost
rabbitmqPort: 5672



#camunda.bpm:
#  admin-user:
#    id: demo
#    password: demo
#    firstName: Demo
#  filter:
#    create: All tasks